### PR TITLE
Crash fixed while using repeating groups in V21 and below.

### PR DESCRIPTION
**Pull request by rahimkhalid**
Crash no virtual method getColor while using repeating groups fix for API V21 and below.

### CODE REVIEW

**Comment by rahimkhalid** [comment]
@githengi

**Comment by rahimkhalid** [comment]
@githengi gradle.properties is updated with VERSION_NAME=1.7.5-SNAPSHOT

**Comment by githengi** [comment]
@rahimkhalid I have uploaded the snapshot, just upgrade on your build

**Comment by aurangzaibumer777** [comment]
since we are using **client-chw-core** in dependency and hence cannot change native client form dependency (which is coming from client-chw-core) so when will **client-chw-core** update and use **1.7.5 snapshot** for native-client-form ?

**Pull request merged**
