### PR TITLE
Fix barcode text field bug

### LINKED ISSUE #275: Revert barcode method signature and fix bug
Fixes the bug here https://github.com/OpenSRP/opensrp-client-native-form/pull/272

And reverts the protected method signature `BarcodeFactory#void addOnBarCodeResultListeners(final Context context, final MaterialEditText editText)` to avoid breaking code downstream

### PR DESCRIPTION
**Pull request by vincent-karuri**
Closes #275

### CODE REVIEW

**Comment by vincent-karuri** [comment]
> No need to call `addOnBarCodeResultListeners(context, editText)` multiple times just add it only once inside the `launchBarcodeScanner` method and you will achieve the same result

Cool. I had considered this. However, using the single responsibility principle, a method should ideally do one thing. Thus if it should launch a barcode scanner, that's what it is expected to do with no other side effects.

However, I believe the `onClickListener` can have a bunch of side effects attached to it.

**Comment by vincent-karuri** [comment]
> > No need to call `addOnBarCodeResultListeners(context, editText)` multiple times just add it only once inside the `launchBarcodeScanner` method and you will achieve the same result
> 
> Cool. I had considered this. However, using the single responsibility principle, a method should ideally do one thing. Thus if it should launch a barcode scanner, that's what it is expected to do with no other side effects.
> 
> However, I believe the `onClickListener` can have a bunch of side effects attached to it.

Additionally `addOnBarCodeResultListeners(context, editText)`  is not a computationally intensive operation so this calling it multiple times is not expensive.

**Comment by bennsimon** [comment]
> > > No need to call `addOnBarCodeResultListeners(context, editText)` multiple times just add it only once inside the `launchBarcodeScanner` method and you will achieve the same result
> > 
> > 
> > Cool. I had considered this. However, using the single responsibility principle, a method should ideally do one thing. Thus if it should launch a barcode scanner, that's what it is expected to do with no other side effects.
> > However, I believe the `onClickListener` can have a bunch of side effects attached to it.
> 
> Additionally `addOnBarCodeResultListeners(context, editText)` is not a computationally intensive operation so calling it multiple times is not expensive.

I just think `addOnBarCodeResultListeners(context, editText)` depends on `launchBarcodeScanner` and calling them separately is repetitive

**Comment by vincent-karuri** [comment]
> > > > No need to call `addOnBarCodeResultListeners(context, editText)` multiple times just add it only once inside the `launchBarcodeScanner` method and you will achieve the same result
> > > 
> > > 
> > > Cool. I had considered this. However, using the single responsibility principle, a method should ideally do one thing. Thus if it should launch a barcode scanner, that's what it is expected to do with no other side effects.
> > > However, I believe the `onClickListener` can have a bunch of side effects attached to it.
> > 
> > 
> > Additionally `addOnBarCodeResultListeners(context, editText)` is not a computationally intensive operation so calling it multiple times is not expensive.
> 
> I just think `addOnBarCodeResultListeners(context, editText)` depends on `launchBarcodeScanner` and calling them separately is repetitive

I wouldn't say it depends on it. Both should ideally be able to act separately. 

Another solution would be to combine the call to both functions in another function that describes what is happening. Then call this one function in the `onClickListener`.

**Comment by bennsimon** [comment]
> > > > > No need to call `addOnBarCodeResultListeners(context, editText)` multiple times just add it only once inside the `launchBarcodeScanner` method and you will achieve the same result
> > > > 
> > > > 
> > > > Cool. I had considered this. However, using the single responsibility principle, a method should ideally do one thing. Thus if it should launch a barcode scanner, that's what it is expected to do with no other side effects.
> > > > However, I believe the `onClickListener` can have a bunch of side effects attached to it.
> > > 
> > > 
> > > Additionally `addOnBarCodeResultListeners(context, editText)` is not a computationally intensive operation so calling it multiple times is not expensive.
> > 
> > 
> > I just think `addOnBarCodeResultListeners(context, editText)` depends on `launchBarcodeScanner` and calling them separately is repetitive
> 
> I wouldn't say it depends on it. Both should ideally be able to act separately.
> 
> Another solution would be to combine the call to both functions in another function that describes what is happening. Then call this one function in the `onClickListener`.

Cool i prefer that other way but whichever you decide will be fine

**Pull request merged**
